apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-awskubernetes-java
  labels:
    app: Jenkins-AWSKubernetes-Java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Jenkins-AWSKubernetes-Java
  template:
    metadata:
      labels:
        app: Jenkins-AWSKubernetes-Java
    spec:
      containers:
      - name: jenkins-awskubernetes-java
        image: devops.damand.fr:5000/ajenkins-awskubernetes-java:0.1.0-SNAPSHOT
        ports:
        - containerPort: 8880
